### ISSUE TITLE
【要望】タイマーをページとして開いて常時表示を実現する

### ISSUE THREAD

**Issue by yorumori-0225** [NaoKanata/CircularIndicator#2]
# 問題点
* chromeの拡張アイコンでの残り時間表示のみだと見づらい。
* chrome拡張機能としてポップアップされるウィンドウは表示後別ウィンドウをクリックすると非表示になってしまう。
* chrome拡張機能としてポップアップされるウィンドウを常時表示しておく術はない。

# 提案
ポップアップ画面にボタンを追加し、ボタンをクリックすることによってwebページとしてタイマー画面を表示してはどうか。

**Comment by NaoKanata** [comment]
現状だと下記のように LocalStorage を利用しているため、クロスドメインでデータを共有するような実装が難しい
https://github.com/NaoKanata/CircularIndicator/blob/main/src/App.js#L213-L215

そのため、下記のどちらかの方法で実装を検討する
1. 本リポジトリ内でコンテンツ用のページを作成する（ = シングルドメインで動作する）
2. https://github.com/zendesk/cross-storage を利用してクロスドメイン上で管理できるデータを扱うようにする
